### ISSUE TITLE
Crash creating a world 

### ISSUE THREAD

**Issue by PikachuPlaysSKY** [SilverAndro/Lootbeams#1]
https://pastebin.com/zGkkQbpa

**Comment by SilverAndro** [comment]
Is this still an issue when you use a version that isnt multiple months old

**Comment by PikachuPlaysSKY** [comment]
haha my bad. I would blame the mislabeling on curseforge. that version i had was under 1.17 and i used the quickdownload.

got the new version and still crrashed here
https://pastebin.com/T6XHdmLT

**Comment by SilverAndro** [comment]
Hm interesting thanks, I'll look into this

(Sorry if that comment came off as rude, was meant as a light hearted joke)

**Comment by PikachuPlaysSKY** [comment]
all good. Ill keep on waiting.

**Comment by SilverAndro** [comment]
Ah seems I never properly updated to 1.17, 1.0.1 must have been marked by accident?

Oh well, Ill do a proper update now that i know it breaks

**Comment by SilverAndro** [comment]
2.0.3 supports 1.17
