### ISSUE TITLE
1.19.2 compatibility?

### ISSUE THREAD

**Issue by ccrowles** [SilverAndro/Lootbeams#5]
Your mod seems really good, and so I just wanted to ask if you plan to update it to 1.19.2.

**Comment by SilverAndro** [comment]
It should work, is it broken?

**Comment by ccrowles** [comment]
I haven't tried because the mod is still listed as compatible only up to mc 1.18, not 1.19. I kind of assumed that since 1.19 was such a massive update, it wouldn't be compatible.

**Comment by SilverAndro** [comment]
Generally my mods don't break too often, so worth checking

If you don't mind checking that would be great, I can mark it compatible if it works

Sadly did lose my laptop a bit ago, so can't update the mod itself rn

**Comment by ccrowles** [comment]
Ok, I just tried it on a clean instance with no other mod/texture/shader installed other than Lootbeams and Fabric API, in creative mode. First I dropped a diamond, and it didn't have any beam. Then I dropped a totem of undying, and the game crashed and refused to start again.
Logfile: [here](https://mclo.gs/xpdPTG0)

**Comment by SilverAndro** [comment]
Damn yep ok, definitely broke

Ill update when I can, unfortunately might be a week or more until I have a computer for dev work again

**Comment by ccrowles** [comment]
It's absolutely alright, take your time. I'm already glad that you're willing to fix it to make it compatible

**Comment by ccrowles** [comment]
Wait, does the 1.19.3 port work on 1.19.2 too?

**Comment by SilverAndro** [comment]
No it wont because of Things:tm:

See #6 convo, can upload later
